import { BrowserRouter, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { useEffect, useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { format, parseISO, subDays } from 'date-fns';
import { Toaster, toast } from 'react-hot-toast';
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, Tooltip, PieChart, Pie, Cell, ResponsiveContainer, LineChart, Line } from 'recharts';
import { DragDropContext, Droppable, Draggable } from 'react-beautiful-dnd';
import PageWrapper from './components/layout/PageWrapper';
import Card from './components/ui/Card';
import Button from './components/ui/Button';
import Input from './components/ui/Input';
import Skeleton from './components/ui/Skeleton';
import Modal from './components/ui/Modal';
import { useAuthStore } from './store/authStore';
import { createWorkout, getExercises, getWorkoutById, getWorkouts, updateWorkout, addExerciseToWorkout, addSetToExercise, removeExerciseFromWorkout } from './api/workouts';
import { createBodyMetric, getBodyMetrics } from './api/metrics';
import { createNutritionLog, getNutritionLogs } from './api/nutrition';
import { getBodyweightTrend, getStreak, getWeeklyVolume } from './api/stats';
import { changePassword, deleteMe, updateMe } from './api/users';

const colors = ['#2563eb','#06b6d4','#10b981','#f59e0b','#8b5cf6'];
const isoWeek=(d)=>{const t=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));const day=t.getUTCDay()||7;t.setUTCDate(t.getUTCDate()+4-day);const yStart=new Date(Date.UTC(t.getUTCFullYear(),0,1));const week=Math.ceil((((t-yStart)/86400000)+1)/7);return `${t.getUTCFullYear()}-${String(week).padStart(2,'0')}`};
const vol=(session)=>session.session_exercises?.flatMap(e=>e.sets||[]).reduce((s,x)=>s+(x.reps*x.weight_kg),0)||0;

function Protected({children}){const {token,loading}=useAuthStore(); if(loading)return <Skeleton className='h-screen'/>; return token?children:<Navigate to='/login'/>}

const getErrorMessage = (error) => {
  if (!error) return 'Request failed';
  if (typeof error === 'string') return error;
  if (error.response?.data) {
    const { data } = error.response;
    if (typeof data === 'string') return data;
    if (data.detail) return typeof data.detail === 'string' ? data.detail : JSON.stringify(data.detail);
    if (data.message) return typeof data.message === 'string' ? data.message : JSON.stringify(data.message);
    return JSON.stringify(data);
  }
  if (error.message) return error.message;
  return String(error);
};

export function AuthPage({mode}){const nav=useNavigate();const {login,register}=useAuthStore();const schema=mode==='login'?z.object({email:z.string().email(),password:z.string().min(1)}):z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8),confirm:z.string()}).refine(v=>v.password===v.confirm,{path:['confirm'],message:'Passwords do not match'}); const {register:rf,handleSubmit,formState:{errors,isSubmitting}}=useForm({resolver:zodResolver(schema),defaultValues:mode==='login'?{email:'',password:''}:{name:'',email:'',password:'',confirm:''}});
const onSubmit=async(v)=>{try{if(mode==='login'){await login(v);toast.success('Welcome back');nav('/dashboard');}else{await register({name:v.name,email:v.email,password:v.password});toast.success('Registered, please login');nav('/login');}}catch(e){toast.error(getErrorMessage(e))}};
return <div className='mx-auto mt-16 max-w-md p-4'><Card><h1 className='mb-4 text-2xl font-bold'>{mode==='login'?'Login':'Register'}</h1><form className='space-y-3' onSubmit={handleSubmit(onSubmit)}>{mode!=='login'&&<Input placeholder='Name' {...rf('name')}/>}<Input placeholder='Email' {...rf('email')}/><Input type='password' placeholder='Password' {...rf('password')}/>{mode!=='login'&&<Input type='password' placeholder='Confirm password' {...rf('confirm')}/>}<Button disabled={isSubmitting} className='w-full'>{mode==='login'?'Login':'Create account'}</Button>{Object.values(errors)[0]&&<p className='text-sm text-red-500'>{Object.values(errors)[0].message}</p>}</form></Card></div>}

export function Dashboard(){const [loading,setLoading]=useState(true);const [workouts,setWorkouts]=useState([]);const [trend,setTrend]=useState([]);const [streak,setStreakVal]=useState(0);const [volumeSeries,setVolumeSeries]=useState([]);const [open,setOpen]=useState(false);const nav=useNavigate();
useEffect(()=>{(async()=>{try{const [w,t,s]=await Promise.all([getWorkouts(),getBodyweightTrend(30),getStreak()]);setWorkouts(w);setTrend(t);setStreakVal(s.streak||0);const arr=[];for(let i=7;i>=0;i--){const wk=isoWeek(subDays(new Date(),i*7));const d=await getWeeklyVolume(wk).catch(()=>({}));arr.push({week:wk,...d})}setVolumeSeries(arr);}finally{setLoading(false)}})()},[]);
const thisWeek=useMemo(()=>{const ws=isoWeek(new Date());return workouts.filter(w=>isoWeek(new Date(w.date))===ws)},[workouts]);
if(loading)return <PageWrapper><div className='grid gap-4 md:grid-cols-3'><Skeleton/><Skeleton/><Skeleton/></div></PageWrapper>;
return <PageWrapper><div className='space-y-4'><div className='grid gap-4 md:grid-cols-3'><Card><p>This week sessions</p><p className='text-2xl font-bold'>{thisWeek.length}</p></Card><Card><p>Total volume this week</p><p className='text-2xl font-bold'>{Math.round(thisWeek.reduce((s,x)=>s+vol(x),0))} kg</p></Card><Card><p>Current streak</p><p className='text-2xl font-bold'>{streak} days</p></Card></div><div className='grid gap-4 lg:grid-cols-2'><Card><h3 className='mb-2 font-semibold'>Bodyweight trend</h3><div className='h-64'><ResponsiveContainer><LineChart data={trend}><XAxis dataKey='date' tickFormatter={(d)=>format(parseISO(d),'MMM d')}/><YAxis/><Tooltip/><Line dataKey='weight_kg' stroke={colors[0]}/></LineChart></ResponsiveContainer></div></Card><Card><h3 className='mb-2 font-semibold'>Volume by muscle group</h3><div className='h-64'><ResponsiveContainer><BarChart data={volumeSeries}><XAxis dataKey='week'/><YAxis/><Tooltip/><Bar dataKey='chest' fill={colors[0]}/><Bar dataKey='back' fill={colors[1]}/><Bar dataKey='legs' fill={colors[2]}/></BarChart></ResponsiveContainer></div></Card></div><Button onClick={()=>setOpen(true)}>Quick-log</Button><Modal open={open} onClose={()=>setOpen(false)} title='Quick Log'><Button onClick={async()=>{const session=await createWorkout({date:format(new Date(),'yyyy-MM-dd'),notes:''});toast.success('Session created');setOpen(false);nav(`/workouts/${session.id}`)}}>Start today session</Button></Modal></div></PageWrapper>}

export function Workouts(){const [data,setData]=useState([]);const [loading,setLoading]=useState(true);const [openIds,setOpen]=useState({});const nav=useNavigate(); useEffect(()=>{(async()=>{try{setData(await getWorkouts())}finally{setLoading(false)}})()},[]);
if(loading)return <PageWrapper><Skeleton className='h-32'/></PageWrapper>; return <PageWrapper><div className='mb-4 flex items-center justify-between'><h1 className='text-2xl font-bold'>Workouts</h1><Button onClick={()=>nav('/workouts/new')}>Start new session</Button></div>{data.length===0?<Card><p>No sessions yet.</p><Button className='mt-2' onClick={()=>nav('/workouts/new')}>Create first session</Button></Card>:<div className='space-y-3'>{data.map(s=><Card key={s.id}><button className='flex w-full justify-between text-left' onClick={()=>setOpen((p)=>({...p,[s.id]:!p[s.id]}))}><span>{format(new Date(s.date),'PPP')}</span><span>{s.session_exercises?.length||0} exercises | {Math.round(vol(s))} kg</span></button>{openIds[s.id]&&<div className='mt-3 space-y-2'>{s.session_exercises?.map(e=><div key={e.id}><p className='font-medium'>{e.exercise.name}</p><p className='text-sm text-slate-500'>{e.sets.map(st=>`${st.reps}x${st.weight_kg}kg`).join(', ')||'No sets'}</p></div>)}</div>}</Card>)}</div>}</PageWrapper>}

export function WorkoutSession(){const {id}=useParams();const nav=useNavigate();const [session,setSession]=useState(null);const [exercises,setExercises]=useState([]);const [query,setQuery]=useState('');useEffect(()=>{(async()=>{const s=id==='new'?await createWorkout({date:format(new Date(),'yyyy-MM-dd'),notes:''}):await getWorkoutById(id);setSession(s);setExercises(await getExercises());if(id==='new')nav(`/workouts/${s.id}`,{replace:true})})()},[id]); if(!session)return <PageWrapper><Skeleton/></PageWrapper>;
const addEx=async(ex)=>{await addExerciseToWorkout(session.id,{exercise_id:ex.id,order_index:session.session_exercises.length});setSession(await getWorkoutById(session.id));toast.success('Exercise added')};
const addSet=async(ex)=>{await addSetToExercise(session.id,ex.exercise.id,{set_number:(ex.sets?.length||0)+1,reps:10,weight_kg:20});setSession(await getWorkoutById(session.id));};
const saveNotes=async(e)=>{setSession(await updateWorkout(session.id,{notes:e.target.value}));toast.success('Saved')};
const onDragEnd=async(r)=>{if(!r.destination)return;const list=[...session.session_exercises];const [m]=list.splice(r.source.index,1);list.splice(r.destination.index,0,m);setSession({...session,session_exercises:list});await Promise.all(list.map((x,i)=>addExerciseToWorkout(session.id,{exercise_id:x.exercise.id,order_index:i}).catch(()=>null)));};
const filtered=exercises.filter(e=>e.name.toLowerCase().includes(query.toLowerCase())).slice(0,8);
return <PageWrapper><div className='space-y-4'><h1 className='text-2xl font-bold'>Workout Session</h1><Card><Input placeholder='Search exercise' value={query} onChange={(e)=>setQuery(e.target.value)}/>{query&&<div className='mt-2 max-h-40 space-y-1 overflow-auto'>{filtered.map(ex=><button className='block w-full rounded border p-2 text-left' key={ex.id} onClick={()=>addEx(ex)}>{ex.name} ({ex.muscle_group})</button>)}</div>}</Card><DragDropContext onDragEnd={onDragEnd}><Droppable droppableId='ex'>{(p)=><div ref={p.innerRef} {...p.droppableProps} className='space-y-2'>{session.session_exercises?.map((ex,i)=><Draggable key={String(ex.id)} draggableId={String(ex.id)} index={i}>{(dp)=><Card ref={dp.innerRef} {...dp.draggableProps}><div className='flex justify-between'><h3 {...dp.dragHandleProps} className='font-semibold'>{ex.exercise.name}</h3><button onClick={async()=>{if(confirm('Delete exercise?')){await removeExerciseFromWorkout(session.id,ex.exercise.id);setSession(await getWorkoutById(session.id));}}}>Delete</button></div><div className='mt-2 space-y-2'>{ex.sets?.map(st=><div key={st.id} className='grid grid-cols-2 gap-2'><Input defaultValue={st.reps} onBlur={()=>{}}/><Input defaultValue={st.weight_kg} onBlur={()=>{}}/></div>)}<Button className='mt-2' onClick={()=>addSet(ex)}>Add set</Button></div></Card>}</Draggable>)}{p.placeholder}</div>}</Droppable></DragDropContext><Card><textarea className='w-full rounded border p-2 dark:bg-slate-900' defaultValue={session.notes||''} onBlur={saveNotes} placeholder='Session notes'/></Card><Button onClick={async()=>{await updateWorkout(session.id,{notes:session.notes});toast.success('Session marked complete');nav('/workouts')}}>Mark session complete</Button></div></PageWrapper>}

export function Metrics(){const [range,setRange]=useState(30);const [data,setData]=useState([]);const {register,handleSubmit,reset}=useForm(); const load=async()=>setData(await getBodyMetrics({limit:1000}));useEffect(()=>{load()},[]); const filt=range==='all'?data:data.filter(x=>new Date(x.date)>=subDays(new Date(),Number(range))); const stats={start:filt[0]?.weight_kg,current:filt.at(-1)?.weight_kg};
return <PageWrapper><div className='space-y-4'><Card><form className='grid gap-2 md:grid-cols-4' onSubmit={handleSubmit(async(v)=>{await createBodyMetric({date:format(new Date(),'yyyy-MM-dd'),weight_kg:Number(v.weight_kg),body_fat_pct:v.body_fat_pct?Number(v.body_fat_pct):null});toast.success('Metric logged');reset();load();})}><Input placeholder='Weight kg' {...register('weight_kg')}/><Input placeholder='Body fat %' {...register('body_fat_pct')}/><Button>Log today</Button></form></Card><Card><div className='mb-2 flex gap-2'>{['30','60','90','all'].map(r=><button key={r} className='rounded border px-2 py-1' onClick={()=>setRange(r)}>{r}</button>)}</div><div className='h-72'><ResponsiveContainer><AreaChart data={filt}><XAxis dataKey='date'/><YAxis/><Tooltip/><Area dataKey='weight_kg' stroke={colors[0]} fill={colors[0]} fillOpacity={0.2}/></AreaChart></ResponsiveContainer></div></Card><div className='grid gap-3 md:grid-cols-3'><Card>Starting: {stats.start ?? '-'} kg</Card><Card>Current: {stats.current ?? '-'} kg</Card><Card>Change: {stats.start&&stats.current?(stats.current-stats.start).toFixed(1):'-'} kg</Card></div></div></PageWrapper>}

export function Nutrition(){const {register,handleSubmit,reset}=useForm();const [logs,setLogs]=useState([]);const load=async()=>setLogs(await getNutritionLogs({limit:1000}));useEffect(()=>{load()},[]);const week=logs.slice(-7).map(l=>({date:l.date,calories:l.calories}));const day=logs.at(-1);
return <PageWrapper><div className='space-y-4'><Card><form className='grid gap-2 md:grid-cols-5' onSubmit={handleSubmit(async(v)=>{await createNutritionLog({date:format(new Date(),'yyyy-MM-dd'),calories:Number(v.calories),protein_g:Number(v.protein_g),carbs_g:Number(v.carbs_g),fat_g:Number(v.fat_g)});toast.success('Nutrition logged');reset();load();})}><Input placeholder='Calories' {...register('calories')}/><Input placeholder='Protein' {...register('protein_g')}/><Input placeholder='Carbs' {...register('carbs_g')}/><Input placeholder='Fat' {...register('fat_g')}/><Button>Save</Button></form></Card><div className='grid gap-4 lg:grid-cols-2'><Card><h3>Weekly summary</h3><div className='h-64'><ResponsiveContainer><BarChart data={week}><XAxis dataKey='date'/><YAxis/><Tooltip/><Bar dataKey='calories' fill={colors[1]}/></BarChart></ResponsiveContainer></div></Card><Card><h3>Macro split (selected day)</h3><div className='h-64'>{day?<ResponsiveContainer><PieChart><Pie data={[{name:'Protein',value:day.protein_g},{name:'Carbs',value:day.carbs_g},{name:'Fat',value:day.fat_g}]} dataKey='value'>{colors.map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer>:<p>No day selected</p>}</div></Card></div></div></PageWrapper>}

export function Profile(){const {user,logout}=useAuthStore();const {register:rf,handleSubmit}=useForm({defaultValues:{name:user?.name,email:user?.email}});const {register:pf,handleSubmit:ph}=useForm();
return <PageWrapper><div className='space-y-4'><Card><h3 className='mb-2 font-semibold'>Profile</h3><form className='space-y-2' onSubmit={handleSubmit(async(v)=>{await updateMe(v);toast.success('Profile updated')})}><Input {...rf('name')}/><Input {...rf('email')}/><Button>Save profile</Button></form></Card><Card><h3 className='mb-2 font-semibold'>Change password</h3><form className='space-y-2' onSubmit={ph(async(v)=>{try{await changePassword(v);toast.success('Password changed')}catch{toast.error('Password change endpoint unavailable on current backend')}})}><Input type='password' placeholder='Old password' {...pf('old_password')}/><Input type='password' placeholder='New password' {...pf('new_password')}/><Input type='password' placeholder='Confirm password' {...pf('confirm_password')}/><Button>Change password</Button></form></Card><Card><h3 className='mb-2 font-semibold text-red-500'>Danger zone</h3><Button className='bg-red-600 hover:bg-red-700' onClick={async()=>{const text=prompt('Type DELETE to confirm');if(text==='DELETE'){await deleteMe();await logout();toast.success('Account deleted')}}}>Delete account</Button></Card></div></PageWrapper>}

export default function App(){const {hydrate,isDark,setTheme}=useAuthStore();useEffect(()=>{hydrate();setTheme(isDark);},[]);return <BrowserRouter><Toaster position='top-right'/><Routes><Route path='/login' element={<AuthPage mode='login'/>}/><Route path='/register' element={<AuthPage mode='register'/>}/><Route path='/dashboard' element={<Protected><Dashboard/></Protected>}/><Route path='/workouts' element={<Protected><Workouts/></Protected>}/><Route path='/workouts/new' element={<Protected><WorkoutSession/></Protected>}/><Route path='/workouts/:id' element={<Protected><WorkoutSession/></Protected>}/><Route path='/metrics' element={<Protected><Metrics/></Protected>}/><Route path='/nutrition' element={<Protected><Nutrition/></Protected>}/><Route path='/profile' element={<Protected><Profile/></Protected>}/><Route path='*' element={<Navigate to='/dashboard'/>}/></Routes></BrowserRouter>}


